sudo: required
language: generic
services:
  - docker
env:
  - SERVICE=autopep8
  - SERVICE=beautysh
  - SERVICE=clang-format
  - SERVICE=crystal
  - SERVICE=elm-format
  - SERVICE=goimports
  - SERVICE=ocp-indent
  - SERVICE=php-cs-fixer
  - SERVICE=phpcbf
  - SERVICE=puppet-lint
  - SERVICE=rscript
  - SERVICE=rubocop
  - SERVICE=ruby-beautify
  - SERVICE=sass-convert
  - SERVICE=sqlformat
  - SERVICE=uncrustify
script:
  - docker-compose build "$SERVICE"
  - docker-compose up "$SERVICE"
